In [1]:
import pandas as pd

In [5]:
csv = "Final_with_School_names.csv"
df = pd.read_csv(csv, encoding="ISO-8859-1")
df

,Unnamed: 0,School Name,Starting Median Salary,Mid-Career Median Salary,Mid-Career 90th Percentile Salary,MORTGAGE,RENT,ELECTRICITY,GAS,EAT-IN,PHONE,HLTH & WELL,VET,REGION,School ID
0,0,University of Oklahoma,44700.0,82900.0,167000.0,247758.0,776.12,154.08,2.18,13.32,164.24,680.75,46.79,0,0
1,1,Oklahoma State University,42800.0,80700.0,151000.0,247758.0,776.12,154.08,2.18,13.32,164.24,680.75,46.79,0,1
2,2,University of Louisiana (UL) at Lafayette,41100.0,76300.0,163000.0,259903.0,814.16,183.42,2.50,14.38,195.52,654.49,48.02,0,3
3,3,University of Colorado Denver,46100.0,84400.0,144000.0,463245.0,1451.00,156.76,2.75,14.37,167.10,790.34,55.28,2,4
4,4,Regis University,48300.0,73800.0,117000.0,463245.0,1451.00,156.76,2.75,14.37,167.10,790.34,55.28,2,5
5,5,University of Akron,41100.0,70300.0,127000.0,343877.0,1077.00,162.63,2.85,14.90,173.36,631.23,43.29,1,7
6,6,Southern Illinois University Carbondale,43000.0,72500.0,139000.0,285928.0,895.69,161.29,2.68,14.33,171.93,759.56,49.46,1,8
7,7,San Francisco State University (SFSU),47300.0,86400.0,150000.0,1146835.0,3593.00,182.92,3.51,18.87,194.98,901.42,62.84,3,9
8,8,Georgetown University,55000.0,110000.0,248000.0,859866.0,2694.00,162.13,2.73,16.14,172.82,724.30,50.44,0,10
9,9,George Washington University (GWU),47000.0,97900.0,194000.0,859866.0,2694.00,162.13,2.73,16.14,172.82,724.30,50.44,0,11
10,10,"American University, Washington D.C.",45300.0,90800.0,169000.0,859866.0,2694.00,162.13,2.73,16.14,172.82,724.30,50.44,0,12
11,11,Howard University,46900.0,81800.0,138000.0,859866.0,2694.00,162.13,2.73,16.14,172.82,724.30,50.44,0,13
12,12,Baylor University,48300.0,88600.0,200000.0,282805.0,885.91,177.55,2.53,12.14,189.26,695.78,49.00,0,14
13,13,University of Utah,45400.0,83200.0,148000.0,320281.0,1003.00,130.77,2.80,14.31,139.40,695.78,49.26,2,15
14,14,Penn State Harrisburg,45700.0,74000.0,150000.0,321322.0,1007.00,199.68,2.76,14.51,212.86,662.74,50.90,4,16
15,15,Stanford University,70400.0,129000.0,257000.0,2140883.0,6706.00,181.74,3.16,21.68,193.73,1017.01,65.26,3,17
16,16,University of Puget Sound,46600.0,81500.0,137000.0,337631.0,1058.00,190.63,2.54,16.14,203.20,914.18,59.65,2,18
17,17,"University of Nevada, Reno (UNR)",46500.0,82900.0,143000.0,370596.0,1161.00,141.84,2.95,14.68,151.20,827.11,58.21,2,19
18,18,Ursinus College,42100.0,80000.0,160000.0,828384.0,2595.00,208.74,3.00,17.05,222.51,793.34,55.18,4,20
19,19,Gonzaga University,44900.0,76000.0,138000.0,320281.0,1003.00,126.75,2.93,14.23,135.11,851.89,50.23,2,21
20,20,Wentworth Institute of Technology,53000.0,96700.0,153000.0,717943.0,2249.00,236.57,2.89,15.52,252.17,1014.76,66.81,4,22
21,21,Boston University,49000.0,93900.0,193000.0,717943.0,2249.00,236.57,2.89,15.52,252.17,1014.76,66.81,4,23
22,22,Northeastern University,50500.0,86400.0,159000.0,717943.0,2249.00,236.57,2.89,15.52,252.17,1014.76,66.81,4,24
23,23,University of Massachusetts (UMass) Boston,45600.0,78200.0,151000.0,717943.0,2249.00,236.57,2.89,15.52,252.17,1014.76,66.81,4,25
24,24,Suffolk University,42100.0,74000.0,145000.0,717943.0,2249.00,236.57,2.89,15.52,252.17,1014.76,66.81,4,26
25,25,Wayne State University,42800.0,76100.0,139000.0,326527.0,1023.00,171.18,2.82,13.32,182.47,707.02,50.03,1,27
26,26,"University of Nevada, Las Vegas (UNLV)",45200.0,71600.0,128000.0,376148.0,1178.00,151.23,2.96,15.26,161.21,770.83,51.52,2,28
27,27,University of Alabama at Birmingham (UAB),39200.0,70100.0,125000.0,299808.0,939.17,169.00,2.38,14.02,180.15,628.96,47.20,0,29
28,28,Evergreen State College,39500.0,63900.0,120000.0,343530.0,1076.00,179.56,3.40,15.79,191.41,884.91,49.77,2,30
29,29,St. Cloud State University,41800.0,71400.0,126000.0,268231.0,840.25,144.19,2.68,16.71,153.70,875.16,52.91,1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,115,Carnegie Mellon University (CMU),61800.0,111000.0,209000.0,317505.0,994.61,184.43,2.78,16.21,196.59,704.03,50.13,4,130
116,116,Duquesne University,40700.0,84400.0,131000.0,317505.0,994.61,184.43,2.78,16.21,196.59,704.03,50.13,4,131
117,117,University of Arkansas,44100.0,82800.0,160000.0,263026.0,823.95,158.61,2.22,13.70,169.07,663.50,50.49,0,133
118,118,University of South Florida (USF),41100.0,71100.0,131000.0,266843.0,835.90,194.99,2.77,14.68,207.85,737.80,49.93,0,136
119,119,University of Arizona,47500.0,86100.0,160000.0,277600.0,869.60,151.23,2.52,15.07,161.21,759.56,52.14,2,137
120,120,University of Maryland Baltimore County (UMBC),47000.0,77800.0,130000.0,509743.0,1597.00,179.56,2.69,15.74,191.41,687.52,54.40,0,138
121,121,Iowa State University,45400.0,84600.0,147000.0,331038.0,1037.00,133.63,2.79,13.32,142.44,748.31,46.22,1,139
122,122,Kansas State University (KSU),43300.0,79000.0,138000.0,294256.0,921.78,149.39,2.39,13.84,159.24,710.03,48.79,1,140
123,123,"University of California, San Diego (UCSD)",51100.0,101000.0,177000.0,817185.0,2560.00,192.64,3.36,16.57,205.35,806.85,52.55,3,141
124,124,San Diego State University (SDSU),46200.0,85200.0,158000.0,817185.0,2560.00,192.64,3.36,16.57,205.35,806.85,52.55,3,142
125,125,University of Wisconsin (UW) Green Bay,35800.0,60600.0,102000.0,281070.0,880.47,172.86,2.62,13.37,184.26,780.58,47.56,1,143
126,126,University of Michigan,52700.0,93000.0,182000.0,407378.0,1276.00,157.10,2.57,16.20,167.46,935.20,48.90,1,144
127,127,Kent State University,38700.0,62600.0,124000.0,546401.0,1712.00,162.63,2.85,14.90,173.36,631.23,43.29,1,146
128,128,Northwestern University,52700.0,95900.0,205000.0,854777.0,2678.00,151.23,3.30,15.89,161.21,760.32,59.09,1,147
129,129,University of Wisconsin (UW) Madison,48900.0,87800.0,170000.0,379618.0,1189.00,176.38,2.80,15.11,188.01,918.68,54.61,1,148
130,130,University of Alabama at Huntsville (UAH),43100.0,82700.0,132000.0,258168.0,808.73,183.92,2.49,14.10,196.06,725.05,55.12,0,149
131,131,University of Washington (UW),48800.0,85300.0,149000.0,673874.0,2111.00,206.39,3.47,18.60,220.00,932.20,69.64,2,150
132,132,Seattle University,48300.0,82800.0,150000.0,673874.0,2111.00,206.39,3.47,18.60,220.00,932.20,69.64,2,151
133,133,"University of California, Berkeley",59900.0,112000.0,201000.0,1128030.0,3534.00,190.46,3.40,18.42,203.03,923.93,62.69,3,152
134,134,University of Texas at El Paso (UTEP),43400.0,72100.0,133000.0,271701.0,851.12,155.25,2.66,15.28,165.49,726.55,45.04,0,153
135,135,Arkansas State University (ASU),38700.0,63300.0,118000.0,257821.0,807.64,146.03,2.26,13.30,155.67,613.21,45.91,0,155
136,136,University of Virginia (UVA),52700.0,103000.0,215000.0,376495.0,1179.00,159.11,2.24,15.52,169.61,829.37,59.86,0,156
137,137,Florida State University (FSU),42100.0,73000.0,156000.0,315423.0,988.08,144.36,2.43,16.13,153.88,739.30,51.06,0,157
138,138,"Wesleyan University (Middletown, Connecticut)",46500.0,97900.0,215000.0,616230.0,1930.00,161.62,2.94,14.77,172.29,852.64,60.58,4,158
139,139,Eastern Washington University,38600.0,70900.0,117000.0,336194.0,1053.00,126.75,2.93,14.23,135.11,851.89,50.23,2,159
140,140,Widener University,52900.0,83400.0,138000.0,244957.0,767.34,208.74,3.00,17.05,222.51,793.34,55.18,4,160
141,141,University of Nebraska,45700.0,80900.0,156000.0,286622.0,897.86,120.21,2.66,14.12,128.14,768.57,53.22,1,161
142,142,Lamar University,46500.0,79400.0,158000.0,311953.0,977.21,216.11,2.47,13.19,230.37,683.01,50.23,0,162
143,143,Tennessee Technological University,46200.0,80000.0,121000.0,237695.0,744.60,166.99,2.26,12.57,178.01,672.51,51.83,0,163
144,144,"California State University, Sacramento (CSUS)",47800.0,82400.0,154000.0,474696.0,1487.00,149.72,3.20,17.13,159.60,778.34,56.15,3,164

In [4]:
southern_df = df.loc[df['REGION'] == 'Southern']

southern_df

Empty DataFrame
Columns: [Unnamed: 0, School Name, Starting Median Salary, Mid-Career Median Salary, Mid-Career 90th Percentile Salary, MORTGAGE, RENT, ELECTRICITY, GAS, EAT-IN, PHONE, HLTH & WELL, VET, REGION, School ID]
Index: []